categories = {
    'Neurological Disorders': [
        "Leukoencephalopathy with brainstem and spinal cord involvement and lactate elevation",
        "Wallenberg's Syndrome",
        "Machado-Joseph Disease",
        "Menkes Disease",
        "Myoclonic epilepsy myopathy sensory ataxia",
        "Parkinson disease type 9",
        "Leigh's Disease",
        "Spinocerebellar ataxia autosomal recessive 8",
        "Craniopharyngioma",
        "Agenesis of the Corpus Callosum",
        "Amyloidosis and Kidney Disease",
        "Progressive supranuclear palsy",
        "Progressive Multifocal Leukoencephalopathy",
        "Spinal muscular atrophy with progressive myoclonic epilepsy",
        "Spinal muscular atrophy with respiratory distress type 1",
        "Spinal muscular atrophy with progressive myoclonic epilepsy",
        "Cerebral Arteriosclerosis",
        "Pontocerebellar hypoplasia type 1",
        "Chronic hiccups",
        "Deep Brain Stimulation for Parkinson's Disease",
        "polymicrogyria",
        "Pudendal Neuralgia"
    ],
    'Genetic Disorders': [
        "Crome syndrome",
        "nonsyndromic holoprosencephaly",
        "familial cylindromatosis",
        "Pierson syndrome",
        "familial multiple trichoepithelioma",
        "autosomal dominant hypocalcemia",
        "autosomal recessive primary microcephaly",
        "hystrix-like ichthyosis with deafness",
        "familial hypobetalipoproteinemia",
        "GM2-gangliosidosis, AB variant",
        "fetal hemoglobin quantitative trait locus 1",
        "arginase deficiency",
        "DOORS syndrome",
        "congenital mirror movement disorder",
        "familial HDL deficiency",
        "Achromatopsia",
        "Alveolar capillary dysplasia with misalignment of pulmonary veins",
        "autosomal recessive nonsyndromic congenital nuclear cataract",
        "Paroxysmal nocturnal hemoglobinuria",
        "familial glucocorticoid deficiency",
        "monilethrix",
        "familial cold autoinflammatory syndrome",
        "centronuclear myopathy",
        "Trisomy 2 mosaicism",
        "Congenital radio-ulnar synostosis",
        "agammaglobulinemia 4",
        "Maturity-onset diabetes of the young, type 8",
        "asphyxiating thoracic dystrophy 3",
        "Spinal muscular atrophy with respiratory distress type 1",
        "glycerol kinase deficiency",
        "Alpha-mannosidosis",
        "Beta-mannosidosis",
        "Fanconi Bickel syndrome",
        "Fragile X syndrome",
        "Familial erythema nodosum",
        "Dentinogenesis imperfecta",
        "Carbamoyl phosphate synthetase 1 deficiency",
        "systemic mastocytosis with associated hematologic neoplasm"
    ],
    'Gastrointestinal Disorders': [
        "Primary Biliary Cirrhosis",
        "Chronic Fatigue Syndrome",
        "Hemochromatosis",
        "Autoimmune Hepatitis",
        "Gastric cancer",
        "Ulcerative Colitis",
        "Barretts esophagus",
        "Coats plus syndrome",
        "Primary gastrointestinal melanoma",
        "Irritable bowel syndrome",
        "Pudendal Neuralgia"
    ],
    'Endocrine Disorders': [
        "Diabetes and Pregnancy",
        "Diabetes Medicines",
        "Thyroid Diseases",
        "Congenital adrenal hyperplasia",
        "Ovarian cysts",
        "Graves disease",
        "adrenal gland hypoplasia, X-linked",
        "Pancreatic Neuroendocrine Tumors (Islet Cell Tumors)",
        "Congenital lobar emphysema",
        "cortisol-producing adenoma",
        "hypercholesterolemia"
    ],
    'Cancer': [
        "Transitional Cell Cancer of the Renal Pelvis and Ureter",
        "Breast Cancer",
        "Colorectal Cancer",
        "Stomach Cancer",
        "Headache",
        "Lung Cancer",
        "Thyroid Cancer",
        "Renal Cell Cancer",
        "Oral submucous fibrosis",
        "Lymphocytic Choriomeningitis (LCM)",
        "Childhood Brain Tumors",
        "Childhood Astrocytomas",
        "Melanoma",
        "Pancreatic Cancer",
        "Pituitary Tumors",
        "Uterine Sarcoma",
        "Gastrointestinal stromal tumor",
        "Paranasal Sinus and Nasal Cavity Cancer",
        "Anal Cancer",
        "Primary melanoma of the central nervous system",
        "Renal oncocytoma",
        "Cervical Cancer Screening",
        "Prostate Cancer Screening",
        "Metastatic squamous neck cancer with occult primary",
        "Epithelial basement membrane corneal dystrophy",
        "Non-small cell lung cancer",
        "Pleuropulmonary blastoma",
        "Testicular cancer",
        "Hodgkin lymphoma",
        "Hypopharyngeal cancer",
        "Salivary Gland Cancer",
        "Mycosis Fungoides and the Szary Syndrome",
        "Merkel Cell Carcinoma",
        "Basal cell carcinoma",
        "Malignant mesothelioma",
        "Nasopharyngeal Cancer",
        "Parotid cancer",
        "Warthin tumor",
        "Neuroendocrine Tumors"
    ],
    'Autoimmune Disorders': [
        "Lupus Nephritis",
        "Rheumatoid Arthritis",
        "Ulcerative Colitis",
        "Crohn's Disease",
        "Psoriasis",
        "Rheumatoid Arthritis",
        "Sclerosing mesenteritis",
        "Atopic dermatitis",
        "Systemic lupus erythematosus",
        "Sarcoidosis",
        "Antiphospholipid Syndrome",
        "Celiac Disease",
        "Ankylosing spondylitis",
        "Polymyalgia Rheumatica",
        "Autoimmune Hemolytic Anemia",
        "Multiple sclerosis",
        "Sjogren's Syndrome",
        "Myasthenia Gravis",
        "Guillain-Barre Syndrome",
        "Graves' Disease",
        "T-cell immunodeficiency, congenital alopecia, and nail dystrophy",
        "Hashimoto's Thyroiditis"
    ],
    'Cardiovascular Disorders': [
        "Kawasaki Disease",
        "Hypertension",
        "Heart Attack",
        "Cardiomyopathy",
        "Congestive Heart Failure",
        "Deep vein thrombosis",
        "Brugada Syndrome",
        "Fetal arrhythmia",
        "Aortic aneurysm",
        "Tachycardia, Ventricular",
        "Tachycardia, Supraventricular",
        "Intracranial aneurysm"
    ],
    'Respiratory Disorders': [
        "Asthma",
        "COPD",
        "Pulmonary embolism",
        "Sarcoidosis",
        "Bronchitis",
        "Emphysema",
        "Asbestosis",
        "Pneumonia",
        "Pulmonary hypertension",
        "Cystic fibrosis",
        "Pleural effusion",
        "Pulmonary fibrosis",
        "Pneumothorax",
        "Respiratory syncytial virus infection",
        "Obstructive sleep apnea",
        "Primary ciliary dyskinesia"
    ],
    'Musculoskeletal Disorders': [
        "Osteoporosis",
        "Osteoarthritis",
        "Rheumatoid Arthritis",
        "Ankylosing spondylitis",
        "Spondylolisthesis",
        "Fibromyalgia",
        "Carpal tunnel syndrome",
        "Gout",
        "Paget's Disease of Bone",
        "Polymyalgia Rheumatica",
        "Muscular dystrophy",
        "Duchenne muscular dystrophy",
        "Becker muscular dystrophy",
        "Myotonic dystrophy",
        "Facioscapulohumeral muscular dystrophy",
        "Limb-girdle muscular dystrophy",
        "Emery-Dreifuss muscular dystrophy",
        "Congenital muscular dystrophy",
        "Oculopharyngeal muscular dystrophy",
        "Distal muscular dystrophy",
        "Dermatomyositis",
        "Polymyositis",
        "Juvenile Idiopathic Arthritis",
        "Osteogenesis imperfecta"
    ],
    'Renal Disorders': [
        "Polycystic Kidney Disease",
        "Renal Cell Carcinoma",
        "Kidney Stones",
        "Renal Hypertension",
        "Acute Kidney Injury",
        "Chronic Kidney Disease",
        "Alport Syndrome",
        "Bartter Syndrome",
        "Fabry Disease",
        "Gitelman Syndrome",
        "Liddle Syndrome",
        "Nephrotic Syndrome",
        "Renal Osteodystrophy",
        "Renal Tubular Acidosis",
        "Urolithiasis"
    ],
    'Hematological Disorders': [
        "Anemia",
        "Leukemia",
        "Lymphoma",
        "Thrombocytopenia",
        "Hemophilia",
        "Von Willebrand Disease",
        "Sickle Cell Disease",
        "Polycythemia Vera",
        "Essential Thrombocythemia",
        "Myelodysplastic Syndromes",
        "Aplastic Anemia",
        "Hemochromatosis",
        "Thalassemia",
        "Neutropenia",
        "Idiopathic thrombocytopenic purpura"
    ],
    'Psychiatric Disorders': [
        "Schizophrenia",
        "Bipolar Disorder",
        "Major Depressive Disorder",
        "Anxiety Disorders",
        "Obsessive-Compulsive Disorder",
        "Post-Traumatic Stress Disorder",
        "Attention-Deficit/Hyperactivity Disorder",
        "Autism Spectrum Disorder",
        "Borderline Personality Disorder",
        "Dissociative Identity Disorder",
        "Panic Disorder",
        "Social Anxiety Disorder",
        "Generalized Anxiety Disorder",
        "Eating Disorders (Anorexia Nervosa, Bulimia Nervosa, Binge-Eating Disorder)",
        "Insomnia Disorder",
        "Narcolepsy",
        "Sleep Apnea",
        "Restless Legs Syndrome",
        "Hypersomnia",
        "REM Sleep Behavior Disorder",
        "Kleine-Levin Syndrome",
        "Delayed Sleep Phase Disorder",
        "Non-24-Hour Sleep-Wake Disorder",
        "Substance Use Disorders (Alcohol Use Disorder, Opioid Use Disorder, Cocaine Use Disorder, etc.)",
        "Gambling Disorder",
        "Internet Gaming Disorder",
        "Excoriation (Skin-Picking) Disorder",
        "Trichotillomania (Hair-Pulling Disorder)",
        "Body Dysmorphic Disorder",
        "Hoarding Disorder",
        "Disruptive Mood Dysregulation Disorder",
        "Oppositional Defiant Disorder",
        "Conduct Disorder",
        "Intermittent Explosive Disorder",
        "Dissociative Disorders (Depersonalization/Derealization Disorder, Dissociative Amnesia, etc.)",
        "Somatic Symptom Disorder",
        "Illness Anxiety Disorder",
        "Conversion Disorder",
        "Factitious Disorder",
        "Intrahepatic cholestasis of pregnancy",
        "Trichotillomania",
        "Eating Disorders (Anorexia Nervosa, Bulimia Nervosa, Binge-Eating Disorder)"
    ],
}